name: flutter_order_app
description: An order taking app built with Flutter

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.5
  path: ^1.8.3
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  excel: ^2.1.0
  uuid: ^4.4.0
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  connectivity_plus: ^6.0.3
  http: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/retailTrack.png"
  web:
    generate: true
    image_path: "assets/retailTrack.png"

flutter:
  uses-material-design: true
  assets:
    - assets/products.xlsx
    - assets/retailTrack.png
    - assets/clients.xlsx
